#DATA SOURCE
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

#Facebook app
REDIRECT_URI: http://localhost:8080/register/facebook
APP_ID: 949905705187730
APP_SECRET: 10b52a2ef982e3e02b66559457fb62be
#APP_ID: 233668646673605
#APP_SECRET: 33b17e044ee6a4fa383f46ec6e28ea1d?