server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/chessapp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    data: classpath:/sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect


authentication:
  oauth:
    client:
      id: chessapp
      secret: secret
    tokenValidityInSeconds: 30000

application:
  project:
    host-api: http://localhost:8080
    host-web: http://localhost:4200

#Facebook app
REDIRECT_URI: http://localhost:8080/tokens/facebook
APP_ID: 949905705187730
APP_SECRET: 10b52a2ef982e3e02b66559457fb62be
#APP_ID: 233668646673605
#APP_SECRET: 33b17e044ee6a4fa383f46ec6e28ea1d?