#DATA SOURCE
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ChessApplication?useSSL=false
#    username: postgres
#    password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    whitelabel:
      enabled: false
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/chess
    username: admin
    password:
    driver-class-name: org.h2.Driver
    data: classpath:/sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


authentication:
  oauth:
    client:
      id: chessapp
      secret: secret
    tokenValidityInSeconds: 180000

application:
  project:
    host-api: http://localhost:8080
    host-web: http://localhost:4200

#Facebook app
REDIRECT_URI: http://localhost:8080/login/facebook
APP_ID: 949905705187730
APP_SECRET: 10b52a2ef982e3e02b66559457fb62be
#APP_ID: 233668646673605
#APP_SECRET: 33b17e044ee6a4fa383f46ec6e28ea1d?